### PR TITLE
UTJS-2 Introduce InjectionContext

### PR DESCRIPTION
**Pull request by mkouba**
- allow InjectionProvider to register a callback invoked when
  the request is handled
- also fix CDIInjectionProvider

### CODE REVIEW

**Comment by mkouba** [comment]
I'm not sure how to support the callbacks in websocket...

**Comment by mkouba** [comment]
@stuartwdouglas Do you plan to merge this PR? If not I will create a different one with minor change to fix the build (CDIInjectionProviderTestCase does not pass on master).

**Comment by stuartwdouglas** [comment]
Sorry, I completely missed the PR email

**Comment by stuartwdouglas** [comment]
I have fixed up websockets.

**Pull request merged**
